config/routes.rb
Rails.application.routes.draw do
  resources :ushio_products
  resources :conceptual_tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conceptual_tag.rb
class ConceptualTag 
  include Neo4j::ActiveNode
  property :name, type: String

  has_many :out, :related, type: :RELATED, model_class: ConceptualTag
  has_many :in, :tagged_products, type: :TAGGED, model_class: UshioProduct


end

app/models/ushio_product.rb
class UshioProduct 
  include Neo4j::ActiveNode
  property :name, type: String
  property :description, type: String
  property :sku, type: String

  #has_many :out, :tagged, type: :PRODUCT_TAGGED, model_class: Product                                       
  has_many :out, :tagged, type: :PRODUCT_TAGGED, model_class: ConceptualTag                                  
  #has_many :out, :related, type: :RELATED, model_class: ConceptualTag                                       
  has_many :both, :related, type: :RELATED, model_class: UshioProduct       

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/conceptual_tags_controller.rb
class ConceptualTagsController < ApplicationController
  before_action :set_conceptual_tag, only: [:show, :edit, :update, :destroy]

  # GET /conceptual_tags
  # GET /conceptual_tags.json
  def index
    @conceptual_tags = ConceptualTag.all
  end

  # GET /conceptual_tags/1
  # GET /conceptual_tags/1.json
  def show
  end

  # GET /conceptual_tags/new
  def new
    @conceptual_tag = ConceptualTag.new
  end

  # GET /conceptual_tags/1/edit
  def edit
  end

  # POST /conceptual_tags
  # POST /conceptual_tags.json
  def create
    @conceptual_tag = ConceptualTag.new(conceptual_tag_params)

    respond_to do |format|
      if @conceptual_tag.save
        format.html { redirect_to @conceptual_tag, notice: 'Conceptual tag was successfully created.' }
        format.json { render :show, status: :created, location: @conceptual_tag }
      else
        format.html { render :new }
        format.json { render json: @conceptual_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conceptual_tags/1
  # PATCH/PUT /conceptual_tags/1.json
  def update
    respond_to do |format|
      if @conceptual_tag.update(conceptual_tag_params)
        format.html { redirect_to @conceptual_tag, notice: 'Conceptual tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @conceptual_tag }
      else
        format.html { render :edit }
        format.json { render json: @conceptual_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conceptual_tags/1
  # DELETE /conceptual_tags/1.json
  def destroy
    @conceptual_tag.destroy
    respond_to do |format|
      format.html { redirect_to conceptual_tags_url, notice: 'Conceptual tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conceptual_tag
      @conceptual_tag = ConceptualTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conceptual_tag_params
      params.require(:conceptual_tag).permit(:name, :related_id, :tagged_products_id)
    end
end

app/controllers/ushio_products_controller.rb
class UshioProductsController < ApplicationController
  before_action :set_ushio_product, only: [:show, :edit, :update, :destroy]

  # GET /ushio_products
  # GET /ushio_products.json
  def index
    @ushio_products = UshioProduct.all
  end

  # GET /ushio_products/1
  # GET /ushio_products/1.json
  def show
  end

  # GET /ushio_products/new
  def new
    @ushio_product = UshioProduct.new
  end

  # GET /ushio_products/1/edit
  def edit
  end

  # POST /ushio_products
  # POST /ushio_products.json
  def create
    @ushio_product = UshioProduct.new(ushio_product_params)

    respond_to do |format|
      if @ushio_product.save
        format.html { redirect_to @ushio_product, notice: 'Ushio product was successfully created.' }
        format.json { render :show, status: :created, location: @ushio_product }
      else
        format.html { render :new }
        format.json { render json: @ushio_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ushio_products/1
  # PATCH/PUT /ushio_products/1.json
  def update
    respond_to do |format|
      if @ushio_product.update(ushio_product_params)
        format.html { redirect_to @ushio_product, notice: 'Ushio product was successfully updated.' }
        format.json { render :show, status: :ok, location: @ushio_product }
      else
        format.html { render :edit }
        format.json { render json: @ushio_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ushio_products/1
  # DELETE /ushio_products/1.json
  def destroy
    @ushio_product.destroy
    respond_to do |format|
      format.html { redirect_to ushio_products_url, notice: 'Ushio product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ushio_product
      @ushio_product = UshioProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ushio_product_params
      params.require(:ushio_product).permit(:name, :description, :sku, :tagged_id, :related_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text) #Allows the ability to render markdown inline. Example: `<%= markdown(@artefact.content) %>`
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: "nofollow", target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/helpers/conceptual_tags_helper.rb
module ConceptualTagsHelper
end

app/helpers/ushio_products_helper.rb
module UshioProductsHelper
end

app/views/conceptual_tags/_form.html.erb
<%= form_for(conceptual_tag) do |f| %>
  <% if conceptual_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conceptual_tag.errors.count, "error") %> prohibited this conceptual_tag from being saved:</h2>

      <ul>
      <% conceptual_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :related_id %>
    <%= f.text_field :related_id %>
  </div>

  <div class="field">
    <%= f.label :tagged_products_id %>
    <%= f.text_field :tagged_products_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conceptual_tags/edit.html.erb
<h1>Editing Conceptual Tag</h1>

<%= render 'form', conceptual_tag: @conceptual_tag %>

<%= link_to 'Show', @conceptual_tag %> |
<%= link_to 'Back', conceptual_tags_path %>

app/views/conceptual_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conceptual Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Related</th>
      <th>Tagged products</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conceptual_tags.each do |conceptual_tag| %>
      <tr>
        <td><%= conceptual_tag.name %></td>
        <td><%= conceptual_tag.related %></td>
        <td><%= conceptual_tag.tagged_products %></td>
        <td><%= link_to 'Show', conceptual_tag %></td>
        <td><%= link_to 'Edit', edit_conceptual_tag_path(conceptual_tag) %></td>
        <td><%= link_to 'Destroy', conceptual_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conceptual Tag', new_conceptual_tag_path %>

app/views/conceptual_tags/new.html.erb
<h1>New Conceptual Tag</h1>

<%= render 'form', conceptual_tag: @conceptual_tag %>

<%= link_to 'Back', conceptual_tags_path %>

app/views/conceptual_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conceptual_tag.name %>
</p>

<p>
  <strong>Related:</strong>
  <%= @conceptual_tag.related %>
</p>

<p>
  <strong>Tagged products:</strong>
  <%= @conceptual_tag.tagged_products %>
</p>

<%= link_to 'Edit', edit_conceptual_tag_path(@conceptual_tag) %> |
<%= link_to 'Back', conceptual_tags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreshagainTemplated</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/components/form.min.css">
    <link rel="stylesheet" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.min.css">
    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/components/form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.8/semantic.min.js"></script>

    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ushio_products/_form.html.erb
<%= form_for(ushio_product) do |f| %>
  <% if ushio_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ushio_product.errors.count, "error") %> prohibited this ushio_product from being saved:</h2>

      <ul>
      <% ushio_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div class="field">
    <%= f.label :tagged_id %>
    <%= f.text_field :tagged_id %>
  </div>

  <div class="field">
    <%= f.label :related_id %>
    <%= f.text_field :related_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ushio_products/edit.html.erb
<h1>Editing Ushio Product</h1>

<%= render 'form', ushio_product: @ushio_product %>

<%= link_to 'Show', @ushio_product %> |
<%= link_to 'Back', ushio_products_path %>

app/views/ushio_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ushio Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Sku</th>
      <th>Tagged</th>
      <th>Related</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ushio_products.each do |ushio_product| %>
      <tr>
        <td><%= ushio_product.name %></td>
        <td><%= ushio_product.description %></td>
        <td><%= ushio_product.sku %></td>
        <td><%= ushio_product.tagged %></td>
        <td><%= ushio_product.related %></td>
        <td><%= link_to 'Show', ushio_product %></td>
        <td><%= link_to 'Edit', edit_ushio_product_path(ushio_product) %></td>
        <td><%= link_to 'Destroy', ushio_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ushio Product', new_ushio_product_path %>

app/views/ushio_products/new.html.erb
<h1>New Ushio Product</h1>

<%= render 'form', ushio_product: @ushio_product %>

<%= link_to 'Back', ushio_products_path %>

app/views/ushio_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ushio_product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ushio_product.description %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @ushio_product.sku %>
</p>

<p>
  <strong>Tagged:</strong>
  <%= @ushio_product.tagged %>
</p>

<p>
  <strong>Related:</strong>
  <%= @ushio_product.related %>
</p>

<%= link_to 'Edit', edit_ushio_product_path(@ushio_product) %> |
<%= link_to 'Back', ushio_products_path %>